---
baseURL: https://www.llgoewer.de/
languageCode: en-us
title: Maiks site
theme: xmin
enableRobotsTXT: true
enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  commitUrl: https://git.llgoewer.de/maik/homepage/commit/

menu:
  main:
    - name: /home/maik
      url: /
      weight: 1
    - name: ~/keys
      url: /keys/
      weight: 2
    - name: ~/git
      url: https://git.llgoewer.de/
      weight: 3
    - name: ~/public
      url: https://s3.llgoewer.de/minio/public/
      weight: 4
...
