baseURL = "https://llgoewer.de/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = 'xmin'
enableRobotsTXT = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "GPG fingerprint"
    url = "/gpg"
    weight = 3
