---
baseURL: https://allgoewer.github.io/homepage/
languageCode: en-us
title: Maiks site
theme: xmin
enableRobotsTXT: true
enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  commitUrl: https://github.com/allgoewer/homepage/commit/

menu:
  main:
    - name: /home/maik
      url: /
      weight: 1
    - name: ~/keys
      url: /keys/
      weight: 2
    - name: ~/git
      url: https://github.com/allgoewer/
      weight: 3
    - name: ~/public
      url: https://s3.llgoewer.de/minio/public/
      weight: 4
    - name: ~/notes
      url: https://notes.llgoewer.de/
      weight: 5
...
