baseURL = "https://www.llgoewer.de/"
languageCode = "en-us"
title = "Maiks site"
theme = 'xmin'
enableRobotsTXT = true

[[menu.main]]
    name = "/home/maik"
    url = "/"
    weight = 1

[[menu.main]]
    name = "~/categories"
    url = "/categories"
    weight = 1

[[menu.main]]
    name = "~/keys"
    url = "/keys"
    weight = 1

[[menu.main]]
    name = "~/git"
    url = "https://www.git.llgoewer.de/"
    weight = 1
